### ISSUE TITLE
UI/UX bugs

### ISSUE THREAD

**Issue by sarthakpranesh** [agnivabasak/Notes-App#2]
1. When no notes are added and the app starts the status bar is hidden but when notes get added the status bar is visible again

2. The top header is too thick when the status bar is not visible

3. Give more top margin on adding note screen on the Title input field. Also having a bit more font size on the title will be nicer.

Will add screenshots below for your reference :small_airplane:

**Comment by sarthakpranesh** [comment]
1 -> 
![5](https://user-images.githubusercontent.com/41206172/80239255-88a88180-867d-11ea-878d-5f790cf68c04.png)
![4](https://user-images.githubusercontent.com/41206172/80239265-8ba37200-867d-11ea-8773-fd4b7c91bba9.png)

2 ->
![1](https://user-images.githubusercontent.com/41206172/80239309-9f4ed880-867d-11ea-8ce8-acc132fe4336.png)

3 -> a bit more space over Enter title
![5](https://user-images.githubusercontent.com/41206172/80239324-a970d700-867d-11ea-8aeb-b4a0b461f8df.png)

**Comment by agnivabasak** [comment]
i will look into it
