### ISSUE TITLE
Integrate react-native-dotenv

### ISSUE THREAD

**Issue by sarthakpranesh** [agnivabasak/Notes-App#4]
Why?
It is very important to separate secrets from your source code. Secrets are API keys or any sort of keys that you would not want to disclose along with the source code as they might provide access to your database, may be used to fetch other more important credentials, etc. Instead, you just share the source code while allowing other people to create their own .env file.

Include the following packages and go through the documentation
- [react-native-dotenv](https://www.npmjs.com/package/react-native-dotenv)

Setup a temp environment variable and log it in ShowScreen
Gist of sets
1. include react-native-dotenv
2. create a .env file in the root of the project and add a temp variable to it of your choice ( also make sure you add this file to .gitignore )
3. import the variable using react-native-dotenv module
4. log the variable

**Comment by agnivabasak** [comment]
Hi , I am trying to include react-native-dotenv to my project . As written in its doc, it is said i need to add some presets to .babelrc file in my root directory . I dont have a .babelrc file in my project root dir . I do have babel-config file though .Should i just go ahead and make the changes in that file ? (Also i have also babel-preset-react-native)

**Comment by sarthakpranesh** [comment]
> Hi , I am trying to include react-native-dotenv to my project . As written in its doc, it is said i need to add some presets to .babelrc file in my root directory . I dont have a .babelrc file in my project root dir . I do have babel-config file though .Should i just go ahead and make the changes in that file ? (Also i have also babel-preset-react-native)

Hey @agnivabasak, yes you can add those presets to your babel-config.js file ( both .babelrc and babel-config do the same thing ).

Also here is a screenshot of one of my babel.config.js files, yours may look different but this is how you need to add the preset
![image](https://user-images.githubusercontent.com/41206172/80305467-87d93200-87da-11ea-8f26-3809d5cf6c50.png)
